<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test-20200124141732" tests="1" file=".py" time="7.851" timestamp="2020-01-24T14:17:43" failures="0" errors="1" skipped="0">
	<testcase classname="Test" name="test_login_form_validations" time="7.851" timestamp="2020-01-24T14:17:43" file="unittests\unity.py" line="17">
		<error type="ElementClickInterceptedException" message="Message: element click intercepted: Element &lt;div class=&quot;card&quot;&gt;...&lt;/div&gt; is not clickable at point (227, 276). Other element would receive the click: &lt;h4 class=&quot;card-title mt-3&quot;&gt;...&lt;/h4&gt;
  (Session info: chrome=79.0.3945.130)
"><![CDATA[Traceback (most recent call last):
  File "c:/Users/srdesai/VeativeWebVR/unittests/unity.py", line 36, in test_login_form_validations
    button.click();
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="card">...</div> is not clickable at point (227, 276). Other element would receive the click: <h4 class="card-title mt-3">...</h4>
  (Session info: chrome=79.0.3945.130)

]]></error>
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
</testsuite>
