<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test-20200124144329" tests="26" file=".py" time="532.830" timestamp="2020-01-24T14:52:30" failures="0" errors="1" skipped="0">
	<testcase classname="Test" name="test_Introduction_to_Complex_Numbers" time="19.009" timestamp="2020-01-24T14:43:56" file="unittests\vaeative_unit.py" line="65">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_Line_and_Plane_of_Symmetry" time="20.753" timestamp="2020-01-24T14:44:17" file="unittests\vaeative_unit.py" line="117">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_Opaque_Translucent_and_Transparent" time="16.472" timestamp="2020-01-24T14:44:33" file="unittests\vaeative_unit.py" line="91">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_Reproductive_Parts_of_a_Flower" time="12.117" timestamp="2020-01-24T14:44:45" file="unittests\vaeative_unit.py" line="78">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_Series_and_Parallel_Circuits" time="13.056" timestamp="2020-01-24T14:44:58" file="unittests\vaeative_unit.py" line="104">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_avatar_monkey" time="12.226" timestamp="2020-01-24T14:45:10" file="unittests\vaeative_unit.py" line="41">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_avatar_snake" time="13.054" timestamp="2020-01-24T14:45:23" file="unittests\vaeative_unit.py" line="53">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_componet_Dominent_recessive_validations" time="28.123" timestamp="2020-01-24T14:45:52" file="unittests\vaeative_unit.py" line="400">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_componet_Galv_validations" time="30.696" timestamp="2020-01-24T14:46:22" file="unittests\vaeative_unit.py" line="378">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_componet_OpaqueT_validations" time="67.388" timestamp="2020-01-24T14:47:38" file="unittests\vaeative_unit.py" line="312">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_componet_Reproduct_part_validations" time="15.951" timestamp="2020-01-24T14:47:54" file="unittests\vaeative_unit.py" line="290">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_componet_atomic_model_validations" time="19.149" timestamp="2020-01-24T14:48:13" file="unittests\vaeative_unit.py" line="356">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_componet_complexNumbers_validations" time="14.439" timestamp="2020-01-24T14:48:27" file="unittests\vaeative_unit.py" line="268">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_componet_dot_structure_validations" time="47.718" timestamp="2020-01-24T14:49:15" file="unittests\vaeative_unit.py" line="445">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_componet_lineandplain_validations" time="15.874" timestamp="2020-01-24T14:49:31" file="unittests\vaeative_unit.py" line="224">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_componet_lines_validations" time="16.150" timestamp="2020-01-24T14:49:47" file="unittests\vaeative_unit.py" line="422">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_componet_series_parallel_validations" time="20.959" timestamp="2020-01-24T14:50:08" file="unittests\vaeative_unit.py" line="334">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_componet_structurePhonel_validations" time="46.041" timestamp="2020-01-24T14:50:54" file="unittests\vaeative_unit.py" line="246">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_humun_brain" time="12.451" timestamp="2020-01-24T14:51:07" file="unittests\vaeative_unit.py" line="143">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_lines" time="12.559" timestamp="2020-01-24T14:51:19" file="unittests\vaeative_unit.py" line="130">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_login_form_validations" time="12.442" timestamp="2020-01-24T14:51:32" file="unittests\vaeative_unit.py" line="156">
		<system-out><![CDATA[logged in successfully
]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_signup_form_validations" time="19.317" timestamp="2020-01-24T14:51:51" file="unittests\vaeative_unit.py" line="184">
		<system-out><![CDATA[signup in successfully
]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_signup_tag_validations" time="11.342" timestamp="2020-01-24T14:52:02" file="unittests\vaeative_unit.py" line="174">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_structure_of_phenol_boy" time="15.885" timestamp="2020-01-24T14:52:18" file="unittests\vaeative_unit.py" line="29">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_structure_of_phenol_girl" time="11.565" timestamp="2020-01-24T14:52:30" file="unittests\vaeative_unit.py" line="17">
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_componet_Humun_brain_validations" time="8.093" timestamp="2020-01-24T14:46:30" file="unittests\vaeative_unit.py" line="467">
		<error type="NoSuchWindowException" message="Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=79.0.3945.130)
"><![CDATA[Traceback (most recent call last):
  File "c:/Users/srdesai/VeativeWebVR/unittests/vaeative_unit.py", line 476, in test_componet_Humun_brain_validations
    loginelement = WebDriverWait(self.driver,10).until(lambda driver:self.driver.find_element_by_xpath(loginurl))
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "c:/Users/srdesai/VeativeWebVR/unittests/vaeative_unit.py", line 476, in <lambda>
    loginelement = WebDriverWait(self.driver,10).until(lambda driver:self.driver.find_element_by_xpath(loginurl))
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=79.0.3945.130)

]]></error>
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
</testsuite>
